stages: 
    - mavenbuild
    - maventest
    
mavenbuild: 
    stage: mavenbuild
    tags:
        - BACKEND
    script: 
        - cd Backend
        - mvn package
        
maven-test:
    stage: maventest
    tags: 
        - BACKEND
    script: 
        - cd Backend
        - mvn test
        - mvn package
