stages: 
    - mavenbuild
    - maventest
    - autodeploy
    - androidbuild
    - androidtest
    
mavenbuild: 
    stage: mavenbuild
    tags:
        - BACKEND
    script: 
        - cd Backend
        - mvn package
        
maven-test:
    stage: maventest
    tags: 
        - BACKEND
    script: 
        - cd Backend
        - mvn test
        - mvn package

auto-deploy:
    stage: autodeploy
    tags:
        - BACKEND
    script: 
        - cd Backend
        - mvn test
        - mvn package
        - sudo mv target/RedPen-1.0-SNAPSHOT.jar /target/web-demo.jar
        - sudo systemctl stop web-demo
        - sudo systemctl start web-demo

android-build:
    image: javiersantos/android-ci:latest
    stage: androidbuild
    before_script:
        - export GRADLE_USER_HOME=`pwd`/.gradle
        - chmod +x ./Frontend/gradlew
    tags:
        - FRONTEND
    script:
        - cd Frontend
        - ./gradlew assemble
    artifacts:
        paths:
            - Frontend/app/build/outputs

unitTests:
    image: javiersantos/android-ci:latest
    stage: androidtest
    before_script:
        - export GRADLE_USER_HOME=`pwd`/.gradle
        - chmod +x ./Frontend/gradlew
    tags:
        - FRONTEND
    script:
        - cd Frontend
        - ./gradlew test
    only:
        refs:
            - master
        changes:
            - Frontend/**/*
